name: run-main
run-name: run-main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: main
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "seasketch"
          POSTGRES_HOST_AUTH_METHOD: "trust"          
          POSTGRES_USER: "postgres"
        ports:
          - 5432:5432          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - run: sudo lsb_release -a 
    
      - name: Test database connection
        run: psql -h 127.0.0.1 -d seasketch -U postgres -c 'SELECT 1;'

      - run: sudo apt-get update

      - run: apt-cache search h3
      
      - run: apt-cache search postgresql

      - run: sudo apt-get install -y build-essential curl git
      
      - run: sudo apt-get install -y pgxnclient postgresql-14 postgresql-14-postgis-3 postgresql-server-dev-14

      - uses: actions/checkout@v3

      - run: cd data/random-sketches && sh ./setup.sh

      - run: ls ./data/random-sketches
      
      - run: sh ./run.sh

      - run: ls

      # Commit all changed files back to the repository
      # - uses: stefanzweifel/git-auto-commit-action@v5
