name: run-main
run-name: run-main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: main
    steps:
      - uses: actions/checkout@v3
    
      - name: install packages
        run: sh setup.sh

      - name: set up database
        run: sh setup_db.sh

      - name: set up test data
        run: cd data/random-sketches && sh ./setup.sh

      - name: set up sql scripts
        run: cd sql && sh ./setup.sh

      - name: set up table
        run: sh ./setup_table.sh

      - name: seed database
        run: sh ./seed_database.sh
      
      - run: sh ./run.sh

      - run: ls

      # Commit all changed files back to the repository
      # - uses: stefanzweifel/git-auto-commit-action@v5
